export const symptomsList = {
  head: [
    "",
    "cognitive impairment",
    "comprehension impairment",
    "confusion",
    "decline in memory or other thinking skills",
    "deformed or misshapen head",
    "dizziness",
    "dull headache",
    "fatigue",
    "fever",
    "fits of rage",
    "head bouncing",
    "head congestion",
    "head injury",
    "head jerking",
    "head shaking",
    "headache",
    "headache behind ears",
    "headache in back of head",
    "headache on one side of head",
    "headache on temples",
    "impulsive behavior",
    "insomnia",
    "memory loss",
    "migraine headache",
    "nasal sinus pain",
    "really sleepy during day",
    "sense of impending doom",
    "severe headache",
    "some face and head muscles are paralyzed or unable to move",
    "sudden severe headache",
    "tension headache",
    "throbbing headache",
    "trouble concentrating",
    "vertigo",
    "weak muscles in face",
  ],
  arms: [
    "arm edema (swelling), unilateral",
    "arm is numb",
    "arm jerking",
    "arm pain",
    "arm pain when moving arms",
    "arm swelling",
    "arm tremor",
    "arms are weak",
    "arms turning blue",
    "asterixis",
    "axillary lymph node enlargement",
    "axillary lymph node tenderness",
    "bicep shaking",
    "burning feeling in arm or leg",
    "can't move arm or leg",
    "can't straighten bent finger(s)",
    "cold hand",
    "compressed nerve in wrist/hand",
    "crackling sound when moving wrist",
    "cramp in my palm",
    "darkened skin on elbow",
    "darkened skin on knuckle(s)",
    "darkening skin on armpit",
    "elbow bones out of place",
    "elbow pain",
    "finger shaking",
    "finger(s) are swollen",
    "finger(s) hurts",
    "finger(s) locks in place",
    "finger(s) turn red",
    "finger(s) turns blue",
    "firm lump in arm pit",
    "forearm feels more sensitive",
    "forearm hurts",
    "forearm itches",
    "hand cramping at night",
    "hand hurts",
    "hand is numb",
    "hand muscle weakness",
    "hand shaking",
    "hand swelling",
    "knuckle joint on hand hurts",
    "left arm hurts",
    "left arm is numb",
    "left shoulder hurts",
    "losing armpit hair",
    "lump in armpit that doesn't move",
    "lump in shoulder",
    "lump on forearm",
    "one arm weak",
    "pain in arm or leg",
    "painful nodules in armpits",
    "paralyzed arm",
    "rash limited to armpit",
    "rash limited to hand",
    "rash limited to legs or arms",
    "rash limited to palm",
    "rash on hand",
    "red bump(s) on elbow",
    "red flaky rash limited to palms or soles",
    "right shoulder hurts",
    "shoulder girdle muscle weakness",
    "shoulder muscle pain",
    "shoulder muscle twitching",
    "shoulder pain",
    "shoulder stiffness",
    "shoulder tender to touch",
    "stiff arm or leg",
    "stiff elbow",
    "stiff hands",
    "subacromial bursal tenderness",
    "subdeltoid bursal tenderness",
    "swollen knuckles",
    "tenderness lateral epicondyle",
    "thumb hurts",
    "tingling and prickling in finger(s)",
    "tingling or pricking of arm",
    "tingling or prickling in forearm",
    "tingling or prickling in hand",
    "trouble moving hands",
    "upper arm pain",
    "very little armpit hair",
    "weak hand grip",
    "wrist hurts when moved",
    "wrist pain",
    "wrist stiffness",
    "wrist swelling",
  ],
  chest: [
    "",
    "abnormal growth of male breasts",
    "barky cough",
    "blood clot traveled to lung",
    "bloody nipple discharge",
    "breast getting bigger",
    "breast hurts",
    "breast redness",
    "breast skin feels like an orange peel",
    "breastbone tender to touch",
    "breasts not developing",
    "breathing too fast",
    "buildup of fluid in lungs",
    "can't cough up mucus or phlegm",
    "chest bones cave in",
    "chest bones stick out",
    "chest hair loss",
    "chest infection",
    "chest pain",
    "chest pain made worse by breathing",
    "chest pain made worse by exertion/exercise",
    "chest tightness",
    "chronic cough (more than 8 weeks) with normal chest xray",
    "congestive heart failure",
    "cough",
    "cough out mucus",
    "cough up thick gunk",
    "cough up yellow gunk",
    "cough with mucus long time",
    "coughing at night",
    "coughing attacks",
    "coughing up bad smelling mucus",
    "coughing up blood",
    "crushing chest pain",
    "dry cough",
    "emphysema",
    "fatty area above collar bone",
    "feeling of pressure in food pipe",
    "fluid leaking from nipple",
    "food gets stuck",
    "forceful cough",
    "growth on nipple",
    "hacking cough",
    "hard for food to go down",
    "hard lump in breast",
    "heartburn",
    "hiccups",
    "infected lump or sore on breast",
    "inflammation of esophagus",
    "lump in breast",
    "lung disease",
    "lung infection",
    "making a whooping noise when inhaling",
    "muscle cramp on trunk",
    "nipple pulling to one side",
    "nipple redness",
    "nipple tender to touch",
    "obese upper body",
    "pain in upper body",
    "palpitations",
    "part of breast skin appears pulled inward",
    "pneumonia",
    "pressure on heart due to fluid buildup",
    "rapid breathing",
    "rash limited to chest",
    "rash limited to under the breast",
    "red, irritated nipple",
    "severe chest pain/pressure",
    "sharp chest pain",
    "shortness breath leaning forward",
    "shortness of breath",
    "shortness of breath when lying flat",
    "shortness of breath with activity",
    "sternal lift",
    "sternal pulsation visible",
    "supraclavicular fossa bruit",
    "supraclavicular lymph node enlargement",
    "swollen breast",
    "tightening of esophagus",
    "tingling or prickling in upper body",
    "upper body muscles shrinking",
    "vomiting after cough",
    "wet cough",
  ],
  abdomin: [
    "",
    "bloated belly",
    "burping",
    "can't digest fatty foods",
    "can't digest some foods",
    "can't eat gluten",
    "diarrhea",
    "diarrhea after meals",
    "epigastric abdominal tenderness",
    "feels like need to pee all the time",
    "gallbladder inflammation",
    "gallstones",
    "indigestion",
    "inflammation of stomach and intestines",
    "liver disease",
    "lower belly bloating",
    "lower stomach pain",
    "nausea",
    "pain around belly button",
    "pain in middle of belly",
    "pain near belly button spreading to lower right side of stomach",
    "pancreas inflammation",
    "rash limited to abdomen",
    "reflux",
    "scarring of the liver",
    "sores, inflammation in colon",
    "stomach cramps",
    "stomach inflammation",
    "stomach pain lower left side",
    "stomach pain lower right side",
    "stomach pain upper left side",
    "stomach pain upper right side",
    "stomach pushes through diaphragm",
    "sudden onset of diarrhea",
    "ulcer in muscle connecting stomach to duodenum",
    "upper belly bloating",
    "upper stomach pain",
    "vomiting blood",
    "watery diarrhea",
  ],
  legs: [
    "ankle pain",
    "ankle redness",
    "ankle swollen",
    "arm or leg is numb",
    "arthritis in big toe",
    "back of knee hurts",
    "back of knee is swollen",
    "back of upper leg is weak",
    "ball of foot joint hurts when move",
    "big toe hurts",
    "big toe hurts when moving",
    "big toe is under the second toe",
    "big toe joint is swollen",
    "big toe joint is tender to touch",
    "bruise on ankle",
    "burning feeling in arm or leg",
    "burning feeling on thigh",
    "calf muscle cramp",
    "calf pain",
    "calf swelling",
    "can't move arm or leg",
    "cramp in thigh muscle",
    "darkened skin on knee",
    "dislocated knee",
    "foot feels weak",
    "foot hurts",
    "foot is numb",
    "foot turning blue",
    "great toe metatarsophalangeal prominence",
    "heel hurts",
    "heel is swollen",
    "heel spur",
    "heel tenderness",
    "hurts to walk",
    "inflamed fluid sac in knee",
    "itching thigh",
    "itchy foot",
    "joint fluid swelling of back off knee joint",
    "knee cracking when moving",
    "knee gets stuck when moving",
    "knee hurts",
    "knee instability",
    "knee joint inflammation",
    "lachman test positive",
    "leg cramp",
    "leg hurts",
    "leg is swollen",
    "leg muscles are weak",
    "leg pain with walking",
    "legs are numb",
    "limping",
    "loss of coordination",
    "lump on ankle",
    "need to move legs",
    "numb thigh muscle",
    "one leg has weak muscles",
    "one leg is red",
    "one leg swollen",
    "outer side of knee hurts",
    "pain in arm or leg",
    "pain in the arch of foot",
    "pain in thigh",
    "paralyzed legs",
    "rash limited to between toes",
    "rash limited to feet",
    "rash limited to legs or arms",
    "rash limited to soles of feet",
    "ridges on shin bone",
    "sharp forward bowing of shin",
    "shin hurts",
    "stiff arm or leg",
    "stiff knee",
    "swollen foot",
    "swollen knee",
    "tender calf muscle",
    "tibial bone mass",
    "tibial deformity",
    "tibial pulse absence",
    "tingling or pricking of leg",
    "tingling or prickling in foot",
    "toe pain",
    "trouble moving foot",
    "trouble moving knee",
    "varicose vein",
    "weakness in lower legs",
  ],
};
